// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Account struct {
	AccountID string  `json:"account_id"`
	Balance   float64 `json:"balance"`
}

type LoginDetail struct {
	AccountID string `json:"account_id"`
	AuthToken string `json:"auth_token"`
}
