// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, accountID string) (Account, error)
	CreateLoginDetail(ctx context.Context, arg CreateLoginDetailParams) (LoginDetail, error)
	GetUserAccount(ctx context.Context, accountID string) (Account, error)
	GetUserLoginDetails(ctx context.Context, accountID string) (LoginDetail, error)
}

var _ Querier = (*Queries)(nil)
