// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
)

const getUserAccount = `-- name: GetUserAccount :one
SELECT account_id, balance FROM accounts
WHERE account_id = $1 LIMIT 1
`

func (q *Queries) GetUserAccount(ctx context.Context, accountID string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getUserAccount, accountID)
	var i Account
	err := row.Scan(&i.AccountID, &i.Balance)
	return i, err
}

const getUserLoginDetails = `-- name: GetUserLoginDetails :one
SELECT account_id, auth_token FROM login_details
WHERE account_id = $1 LIMIT 1
`

func (q *Queries) GetUserLoginDetails(ctx context.Context, accountID string) (LoginDetail, error) {
	row := q.db.QueryRowContext(ctx, getUserLoginDetails, accountID)
	var i LoginDetail
	err := row.Scan(&i.AccountID, &i.AuthToken)
	return i, err
}
